name: "DPZ Bot"

on:
  # run it on every 7 minutes
  schedule:
    - cron: "*/13 * * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build
    - name: Run run
      run: cargo run
      env:
        RSS_URL: https://dailyportalz.jp/feed/headline
        BSKY_ID: ${{ secrets.BSKY_DBZ_BOT_ID }}
        BSKY_PASSWORD: ${{ secrets.BSKY_DPZ_BOT_PASSWORD }}
